services:

  backend:
    build: ./
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.app.loadbalancer.server.port=80
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.app-http.entrypoints=http
      - traefik.http.routers.app-http.rule=Host(`almadati.it`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.app-https.entrypoints=https
      - traefik.http.routers.app-https.rule=Host(`almadati.it`)
      - traefik.http.routers.app-https.tls=true
      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.app-https.tls.certresolver=le
      # https-redirect middleware to redirect HTTP to HTTPS
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
      # Middleware to redirect HTTP to HTTPS
      - traefik.http.routers.app-http.middlewares=https-redirect
      - traefik.http.routers.app-https.middlewares=admin-auth
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public
    volumes:
      - tenants:/code/app/dbfiles
  
  patron:
    build:
      context: ./
      dockerfile: ./patron.dockerfile
    restart: always
    develop:
      watch:
        - action: sync
          path: .
          target: /code/patron
    labels:
      # Enable Traefik for this specific "backend" service
      - traefik.enable=true
      # Define the port inside of the Docker service to use
      - traefik.http.services.panel.loadbalancer.server.port=80
      # Make Traefik use this domain in HTTP
      - traefik.http.routers.panel-http.entrypoints=http
      - traefik.http.routers.panel-http.rule=Host(`unibocconi.almadati.it`)
      # Use the traefik-public network (declared below)
      - traefik.docker.network=traefik-public
      # Make Traefik use this domain in HTTPS
      - traefik.http.routers.panel-https.entrypoints=https
      - traefik.http.routers.panel-https.rule=Host(`unibocconi.almadati.it`)
      - traefik.http.routers.panel-https.tls=true
      # Use the "le" (Let's Encrypt) resolver
      - traefik.http.routers.panel-https.tls.certresolver=le
      # Middleware to redirect HTTP to HTTPS
      - traefik.http.routers.panel-http.middlewares=https-redirect
      - traefik.http.routers.panel-https.middlewares=admin-auth
    networks:
      # Use the public network created to be shared between Traefik and
      # any other service that needs to be publicly available with HTTPS
      - traefik-public
    volumes:
      - patron:/code/patron/dbfiles

volumes:
  tenants:
  patron:

networks:
  traefik-public:
    external: true
